Article: On the estimation of average treatment effects with
right-censored time to event outcome and competing risks

Authors: Brice Ozenne, Thomas Harder Scheike, Laila Staerk, Thomas Alexander Gerds.

Author responsible for writing the code: Brice Ozenne, Thomas Alexander Gerds.

E-mail of the author maintaining the code: tag@biostat.ku.dk

* Content of the folder
The file describes the infra structure of the empirical studies for
the competing-risk-ATE manuscript. This infrastructure is composed of
the following files/folders:
-  [[./simulation-settings.R]] defines the simulation model in the lava
  language and parameters.
-  [[./simulation-functions.R]] defines functions used for running the
  simulations.
-  [[./simulation-run.R]] runs the simulations and export the results
  (datasets in .rds format in the folder Results).
- [[./Results]] outputs of the simulation
- [[./Figures]] figures used in the article and created by [[./figure1.R]],
  [[./figure2.R]], and [[./figure3.R]]
- [[./figure1.R]], [[./figure2.R]], and [[./figure3.R]]: R code used to generate
  figure 1, 2, and 3 of the article.
- [[./Software]] package riskRegression used to run the simulations.

Note: the file [[./figure4.R]] does not precisely replicates the figure 4
of the article.  This is because we are not allowed to make the data
publicly available. Instead we used simulated data.

* Run R code
#+BEGIN_SRC R :exports both :results output :session *R* :cache no
source("simulation-run.R")
#+END_SRC

* R and package versions
#+BEGIN_SRC R  :results output   :exports results  :session *R* :cache yes 
sessionInfo()
#+END_SRC

#+RESULTS[<2018-09-15 13:59:50> b44be29e99bce3ce330d2aefe349e6976f278121]:
#+begin_example
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: openSUSE 13.1 (Bottle) (x86_64)

Matrix products: default
BLAS:   /usr/local/lib64/R/lib/libRblas.so
LAPACK: /usr/local/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] survival_2.44-1.1         riskRegression_2019.10.23
[3] prodlim_2018.04.18        lava_1.6.6
[5] data.table_1.12.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2          mvtnorm_1.0-11      lattice_0.20-38
 [4] zoo_1.8-6           assertthat_0.2.1    digest_0.6.21
 [7] foreach_1.4.7       R6_2.4.0            backports_1.1.5
[10] acepack_1.4.1       MatrixModels_0.4-1  ggplot2_3.2.1
[13] pillar_1.4.2        rlang_0.4.0         lazyeval_0.2.2
[16] multcomp_1.4-10     rstudioapi_0.10     SparseM_1.77
[19] rpart_4.1-15        Matrix_1.2-17       checkmate_1.9.4
[22] splines_3.6.1       stringr_1.4.0       foreign_0.8-72
[25] htmlwidgets_1.5.1   munsell_0.5.0       numDeriv_2016.8-1.1
[28] compiler_3.6.1      xfun_0.10           pkgconfig_2.0.3
[31] base64enc_0.1-3     htmltools_0.4.0     nnet_7.3-12
[34] tidyselect_0.2.5    tibble_2.1.3        gridExtra_2.3
[37] htmlTable_1.13.2    Hmisc_4.2-0         rms_5.1-3.1
[40] codetools_0.2-16    crayon_1.3.4        dplyr_0.8.3
[43] MASS_7.3-51.4       timereg_1.9.4       grid_3.6.1
[46] nlme_3.1-141        polspline_1.1.16    gtable_0.3.0
[49] magrittr_1.5        scales_1.0.0        stringi_1.4.3
[52] latticeExtra_0.6-28 sandwich_2.5-1      Formula_1.2-3
[55] TH.data_1.0-10      RColorBrewer_1.1-2  iterators_1.0.12
[58] tools_3.6.1         cmprsk_2.2-9        glue_1.3.1
[61] purrr_0.3.2         colorspace_1.4-1    cluster_2.1.0
[64] knitr_1.25          quantreg_5.51
#+end_example

